Ci project 4 delivery
chrisignas/Project_DA_Java_EN_Come_to_the_Rescue_of_a_Java_Application pull request #1
Opened 2020-12-17 17:51 UTC by chrisignas

2020-12-17 18:10 UTC, fpatelm requested changes
I don't see this class CountSymptoms on Git.

2020-12-17 18:19 UTC, chrisignas commented on Project02Eclipse/src/com/hemebiotech/analytics/SymptomsWriter.java
> +
CountSymptoms should be added now.

2020-12-21 23:31 UTC, fpatelm commented on Project02Eclipse/src/com/hemebiotech/analytics/CountSymptoms.java
> + * simply counts occurrences of symptoms within a text file
replace "within a text file" by "within a list of strings (symptoms)"

2020-12-21 23:44 UTC, chrisignas commented on Project02Eclipse/src/com/hemebiotech/analytics/CountSymptoms.java
> + * simply counts occurrences of symptoms within a text file
Thank you, corrected.

2020-12-21 23:46 UTC, merged